### ISSUE TITLE
Save option on the HSBCConnect page

### ISSUE THREAD

**Issue by Mberrady** [WorkMAE/CEM-Integration#103]
After I completed entry on the HSBCConnect page, I did not have the option to SAVE AS DRAFT, only Cancel or Submit

![image](https://user-images.githubusercontent.com/40861938/43473412-0d58db54-94be-11e8-81b8-888df97c68d8.png)

**Comment by WorkMAE** [comment]
Submit button should now be showing properly across all forms when appropriate.
