### ISSUE TITLE
File naming convention is out of alignment

### ISSUE THREAD

**Issue by Mberrady** [WorkMAE/CEM-Integration#110]
Under accounts, #xxxxx004 and xxxxx1111 services is AC which should be COS and Possibly ACH,,, is missing Check book code (3ch) has a five digit number          Account # xxxxx0123 services is A 
File naming convention is out of alignment; file name in under file type and file type is missing for LCDB ….T9333 no country is noted for either 
![image](https://user-images.githubusercontent.com/40861938/43598019-b990ee90-9651-11e8-8e24-b54340edade2.png)
![image](https://user-images.githubusercontent.com/40861938/43598049-cbf317ac-9651-11e8-9712-eef51efe0500.png)

**Comment by WorkMAE** [comment]
These should now all be fixed, changed the modifier to check the type of file it is to determine whether certain headers should populate or not.
