### ISSUE TITLE
selected NACHA, but it gives me the option of ACH, ACH&COS and ACH&Positive PAY

### ISSUE THREAD

**Issue by Mberrady** [WorkMAE/CEM-Integration#111]
I only selected NACHA, but it gives me the option of ACH, ACH&COS and ACH&Positive PAY in the Dropbox 
![image](https://user-images.githubusercontent.com/40861938/43599626-357ebcae-9656-11e8-97e4-68b0ee4028ce.png)

**Comment by WorkMAE** [comment]
NACHA is a file format not a service.  What services were selected?

**Comment by Mberrady** [comment]
When I select ACH only 
![image](https://user-images.githubusercontent.com/40861938/43733852-f7b51ad6-9983-11e8-9624-f31478d2cf35.png)
 is only supose to give the option ACH, however, the dropdown give the option of ACHO&COS and ACH &PP
![image](https://user-images.githubusercontent.com/40861938/43733925-318cc434-9984-11e8-8907-2386ce44cfe9.png)

**Comment by WorkMAE** [comment]
OK I will take a look at this.
