### ISSUE TITLE
 H2H/FTP connection info is not lined up properly

### ISSUE THREAD

**Issue by Mberrady** [WorkMAE/CEM-Integration#115]
![image](https://user-images.githubusercontent.com/40861938/43611494-440b6bd4-9677-11e8-93cb-0b189cad6e4b.png)
![image](https://user-images.githubusercontent.com/40861938/43611506-4d36988c-9677-11e8-957d-c271f94846c8.png)

**Comment by WorkMAE** [comment]
This should be fixed now, PGP Encryption label was not displaying properly which I believe was causing the spacing issue.
