### ISSUE TITLE
US Services (Global Disbursement and Virtual Cards) are missing under Accounts 

### ISSUE THREAD

**Issue by Mberrady** [WorkMAE/CEM-Integration#118]
Some of the US Services (Global Disbursement and Virtual Cards) are missing under Accounts and I can’t edit this field. 

GD (ACH)
GD (Wire)
GD (Wire and ACH)
VC

Wire, ACH, COS, Positive Pay & VC
Wire, ACH, COS & VC

Check 2 ACH & VC
![image](https://user-images.githubusercontent.com/40861938/44032990-efb18786-9ed6-11e8-92cd-7d5ef0231694.png)

**Comment by WorkMAE** [comment]
This should be fixed now
