### ISSUE TITLE
No Standard Files and not all services for Payables

### ISSUE THREAD

**Issue by Mberrady** [WorkMAE/CEM-Integration#119]
Only Payable and Receivable are showing under “Set Status For”. Standard files are not showing. 

Also, not all services for US Payable is showing. 
![image](https://user-images.githubusercontent.com/40861938/44033050-217043a2-9ed7-11e8-91e7-f36fbfb0e18b.png)
![image](https://user-images.githubusercontent.com/40861938/44033059-2a17f748-9ed7-11e8-802d-9f1b32201d10.png)

**Comment by WorkMAE** [comment]
This should now be fixed and the following services have been added:

- US GD ACH
- US GD Wire
- CA GD ACH
- CA GD Wire
- Virtual Cards
- Check To ACH

**Comment by Mberrady** [comment]
the services are still missing under set status

**Comment by WorkMAE** [comment]
All of them are listed there...Standard File items sometimes won't appear until you open and then close and re-open the status dropdown...will attempt to resolve these prior to opening the modal.

![image](https://user-images.githubusercontent.com/31932842/44069103-4a57e684-9f4b-11e8-8f74-818bfcf8c04f.png)

**Comment by WorkMAE** [comment]
I put the async ajax calls in the modal resolve which means all the data for the drop-down is gotten BEFORE the modal opens.  This means that all data should be present immediately upon opening the modal in the drop-down and you shouldn't have to wait or re-open to get all the items.
