### ISSUE TITLE
Project status is not displaying correct for both Countries (US/CA). 

### ISSUE THREAD

**Issue by Mberrady** [WorkMAE/CEM-Integration#120]
![image](https://user-images.githubusercontent.com/40861938/44033089-41e374a6-9ed7-11e8-8d27-4203d9e24d0c.png)

**Comment by WorkMAE** [comment]
Now should be resolved

![image](https://user-images.githubusercontent.com/31932842/44045999-3b553bf8-9ef8-11e8-8815-ec48ec6d890a.png)
