### ISSUE TITLE
Active Services vs Live

### ISSUE THREAD

**Issue by Mberrady** [WorkMAE/CEM-Integration#122]
There is an issue where the entire request/project is marked as live and moved to the Live queue even if it’s only one service status changed to live.
![image](https://user-images.githubusercontent.com/40861938/44033310-fd3d7382-9ed7-11e8-89c3-2786e3c966b3.png)

**Comment by WorkMAE** [comment]
This should be resolved, fixed an issue with CA Wire status that caused it not to be checked for Multiple
