### ISSUE TITLE
XMLv2 Integrated Payables testing

### ISSUE THREAD

**Issue by Mberrady** [WorkMAE/CEM-Integration#123]
![image](https://user-images.githubusercontent.com/40861938/44103255-b8aa3060-9fb9-11e8-9636-ec4e49c84d22.png)
![image](https://user-images.githubusercontent.com/40861938/44103272-c76f64a8-9fb9-11e8-9292-4a53a52d2d24.png)

**Comment by WorkMAE** [comment]
Bundle Code is now fixed, it was saved in the Sharepoint List but it was missing from the Object when it loaded in an edit. Have found a major issue affecting all grids when updating more than 1 item at a time. Working on a fix for this.

**Comment by Mberrady** [comment]
![image](https://user-images.githubusercontent.com/40861938/44111038-5c4489d6-9fcf-11e8-8a22-8cf80266d42e.png)
the routing # is not polling

**Comment by WorkMAE** [comment]
This should now be fully resolved, had to write new code for updating items as it was taking the last value in the loop and using that before the item would return, thereby having all items being updated stuck with the same data as the last item in the list.

**Comment by WorkMAE** [comment]
@Mberrady Again, this is the issue I keep referring to with custom drop-down lists with the ability to edit inside the grids.  The data is there, you just cannot see it initially.  Double Click on it and it will appear. There is nothing I can do to fix this, it is an issue with the grid itself currently and I cannot resolve this until they fix it on their end.
