### ISSUE TITLE
Under Swift Fin Concentrator missing data

### ISSUE THREAD

**Issue by Mberrady** [WorkMAE/CEM-Integration#124]
![image](https://user-images.githubusercontent.com/40861938/44106250-23d19286-9fc2-11e8-8ca0-c865c1a284b3.png)

**Comment by WorkMAE** [comment]
@Mberrady Which Project ID is this?  I need to know project ID or Client name so I can see the specific example...this doesn't provide me with any way of identifying which project record it is.
