### ISSUE TITLE
File Naming Convention and accounts  under payabales option isn't pulling on view 

### ISSUE THREAD

**Issue by Mberrady** [WorkMAE/CEM-Integration#125]
![image](https://user-images.githubusercontent.com/40861938/44111239-e7fcd10e-9fcf-11e8-8470-7a1d56cd8d8e.png)
![image](https://user-images.githubusercontent.com/40861938/44111308-103b2260-9fd0-11e8-82a5-3ed39921a80c.png)
So As Accounts 
![image](https://user-images.githubusercontent.com/40861938/44111396-460d0f66-9fd0-11e8-957c-6949569f89e9.png)
![image](https://user-images.githubusercontent.com/40861938/44111417-54838cd2-9fd0-11e8-88db-9f078cd8c324.png)

**Comment by WorkMAE** [comment]
This should be fixed...needed to put added items inside the loop instead of outside
