### ISSUE TITLE
accounts and contacts being duplicated 

### ISSUE THREAD

**Issue by Mberrady** [WorkMAE/CEM-Integration#128]
![image](https://user-images.githubusercontent.com/40861938/44350089-82a3db80-a46c-11e8-91c0-4963e8f115cd.png)

**Comment by WorkMAE** [comment]
I need to know more information than this.  I need to know what the Project ID number is.  I cannot look into issues without knowing basic information about where to begin.

**Comment by WorkMAE** [comment]
I do not see this under any of the accounts Terry has created on or before 8/20 and do not see this in any of the others either.  Cannot reproduce.  Closing issue.
