### ISSUE TITLE
Under Integrated Payable – Services

### ISSUE THREAD

**Issue by Mberrady** [WorkMAE/CEM-Integration#130]
![image](https://user-images.githubusercontent.com/40861938/44465440-8e69dc00-a5eb-11e8-90f1-1ec8705ce599.png)

**Comment by WorkMAE** [comment]
No this is not the case according the Spec I was given from Mahmoud.

The COS Panel should show if any of the following are selected:

- Non-US Accounts ONLY(No CA or US accounts)

- COS(US or CA), Virtual Cards or Check To ACH 

- Wire(US or CA) ONLY IF FileFormat EDI820 or HFS600 is selected

Mahmoud,  please advise as to which is correct.

**Comment by WorkMAE** [comment]
Mahmoud, please advise

**Comment by WorkMAE** [comment]
This is now resolved in the Test site.  Only shows when Us or CA COS is selected.
