### ISSUE TITLE
COS is missing when ACH service is selected 

### ISSUE THREAD

**Issue by Mberrady** [WorkMAE/CEM-Integration#136]
![image](https://user-images.githubusercontent.com/40861938/44676965-b2ba2400-aa02-11e8-9e89-b5d70d791f04.png)

**Comment by WorkMAE** [comment]
COS is COS, why would it show with ACH?

**Comment by WorkMAE** [comment]
Standard File---Delivery Channel goes away once something else is selected other than COS(after COS is selected)

**Comment by WorkMAE** [comment]
Wire, US ARP and ACH(Debit and Credit) cause Delivery Channel to get hidden

**Comment by WorkMAE** [comment]
Should be fixed in test now.  Was using && on condition checks instead of ||
