### ISSUE TITLE
The Receivable section 

### ISSUE THREAD

**Issue by Mberrady** [WorkMAE/CEM-Integration#137]
The Receivable section – file format field keeps disappearing once I fill in
![image](https://user-images.githubusercontent.com/40861938/44726680-455fcf00-aaa6-11e8-8ea2-49e9e0bd68ec.png)
![image](https://user-images.githubusercontent.com/40861938/44726700-5577ae80-aaa6-11e8-87f9-650639067117.png)

**Comment by WorkMAE** [comment]
Please double click on the field again and see if the values are there in edit mode

**Comment by WorkMAE** [comment]
I don't believe this is an issue...I have spoken to this many times, at least 5 separate emails regarding why this happens.  If there is a field in a multi-account grid, such as this, that uses a drop down list and can be edited, the values will save properly but will ONLY SHOW on edit if you double click on the field.  This is an issue with UI-GRID itself, there is NOTHING I can do about this. This is not an error, simply an already known "errata" that you must be aware of.

Went in and checked the field and this is exactly what is happening---see below image as to when I double click on the fields, the values are there.

![image](https://user-images.githubusercontent.com/31932842/45108252-1b438800-b10a-11e8-8c38-9f9d31efffb9.png)
