### ISSUE TITLE
receivebales 

### ISSUE THREAD

**Issue by Mberrady** [WorkMAE/CEM-Integration#138]
![image](https://user-images.githubusercontent.com/40861938/44726855-a687a280-aaa6-11e8-9919-a60cdafb2892.png)

**Comment by WorkMAE** [comment]
I believe it is set to only accept alpha-numeric values but you have a space in there, which is not an alpha numeric value.  It is functioning as was requested it function, now we need to determine if the functionality needs to be changed. 

Mahmoud, does this need to be changed to accept whitespace characters(ie, spaces) 

Mohammed -- You need to double click in the File Format to see them.

**Comment by WorkMAE** [comment]
Updated the Regex to allow whitespace characters and hyphens. Will be fixed once it gets tested to make sure it works and then pushed to production

**Comment by WorkMAE** [comment]
This should now be resolved in the test site.  Translation ID can now accept whitespace and hyphen characters in test.  Please mark this as resolved once you have tested.
