### ISSUE TITLE
Sharepoint bug - Receivable file format field

### ISSUE THREAD

**Issue by Mberrady** [WorkMAE/CEM-Integration#140]
The Receivable section – file format field keeps disappearing once I fill in
![image](https://user-images.githubusercontent.com/40861938/45114218-6e253b80-b11a-11e8-8ffe-28678458019c.png)
![image](https://user-images.githubusercontent.com/40861938/45114245-7c735780-b11a-11e8-9797-ba6c6993c035.png)

**Comment by WorkMAE** [comment]
Once again. Double Click on the file Format field and it will be there.  This is at least the 10th time I've addressed this issue.
