### ISSUE TITLE
Sharepoint bug - Receivable file format field

### ISSUE THREAD

**Issue by Mberrady** [WorkMAE/CEM-Integration#141]
per screenshot below the  drop down option for file type , should there be an option for NACHA/ACH(Standard form view), as well?  If so, it’s not listed.
![image](https://user-images.githubusercontent.com/40861938/45114349-c5c3a700-b11a-11e8-97d2-3216785f9b67.png)
![image](https://user-images.githubusercontent.com/40861938/45114372-d3792c80-b11a-11e8-90be-aaaa7eb072a6.png)

**Comment by WorkMAE** [comment]
Need to check standard file as to why drop downs are not appearing for File Type

**Comment by WorkMAE** [comment]
NACHA shows when the proper inbound/outbound file format is chosen.
