### ISSUE TITLE
Wrong Service name, not all services are displaying under the accounts services

### ISSUE THREAD

**Issue by Mberrady** [WorkMAE/CEM-Integration#144]
Some services are not showing, like COS and Positive Pay  are not showing under Accounts. Need to Correct the ACH service name under Accounts in the view area it should be “ACH” not “ECH”
![image](https://user-images.githubusercontent.com/40861938/45707623-666b8b00-bb4d-11e8-831b-fb4b6ee851c8.png)
![image](https://user-images.githubusercontent.com/40861938/45707632-6e2b2f80-bb4d-11e8-9da6-fb253da40ec0.png)

**Comment by WorkMAE** [comment]
Why would COS be expected to show when its not selected?

**Comment by WorkMAE** [comment]
Make sure all options are available for Wires, ACH, Pos Pay, COS, Virtual Cards, Global Disbursements
