### ISSUE TITLE
Integrated payables client engagement template issue

### ISSUE THREAD

**Issue by Mberrady** [WorkMAE/CEM-Integration#145]
missing Collection App ID  column in edit 
![image](https://user-images.githubusercontent.com/40861938/45892072-1aab2280-bd95-11e8-95dd-28f70a0dc8e7.png)

**Comment by WorkMAE** [comment]
Cannot duplicate issue.  Col AppID column shows whenever ACH Credit, ACH Dir Debit or COS is selected as a service.
