### ISSUE TITLE
Field display - should only list what is selected.

### ISSUE THREAD

**Issue by falamari** [WorkMAE/CEM-Integration#19]
Form fields should only list what client is using.  
Examples.. Vehicles  & Service class fields should just list the vehicles or service class that pertain to client,.  If it is set to N, should not list at all.

Vehicles : ACH: Y COS: Y PosPay: N Wire: Y
Preferred:
Vehicles : ACH, COS, Wire

This is not limited to these 2 fields, should be the case for all that has multiple selectable items.

**Comment by WorkMAE** [comment]
This is set like this in the Test version, will be fixed once that is updated to production
