### ISSUE TITLE
Need drop downs on column headers

### ISSUE THREAD

**Issue by jacobdarling** [WorkMAE/CEM-Integration#2]
more of an enhancement than an issue.  currently i am forced to type in the status (and therefore as a user i need to know all the possible statuses) in order to filter on them.  a filter drop down would alleviate this

**Comment by WorkMAE** [comment]
I think I can do this pretty easily, just need to check the UI-Grid documentation

**Comment by WorkMAE** [comment]
This is fixed and working for the ICE team, will expand to all others coming up

**Comment by WorkMAE** [comment]
Now fixed across the board
