### ISSUE TITLE
Add Files button to Print Page

### ISSUE THREAD

**Issue by FourUnbelievableCoolKids** [WorkMAE/CEM-Integration#20]
When clicking link in email for the project upon assignment, a wonderful overview page pops up.  There are two items to add that would be extremely helpful.

1) Label displaying the GIM
2) The FILE button that opens up the uploaded files for that PRJ

**Comment by WorkMAE** [comment]
The person who created the file is now displayed, working on the other request.

![gimpic](https://user-images.githubusercontent.com/31932842/35349024-ba6ea1aa-0131-11e8-86df-51013cf8b650.PNG)
