### ISSUE TITLE
Links in Email Do not Work (when the project goes live)

### ISSUE THREAD

**Issue by jacobdarling** [WorkMAE/CEM-Integration#22]
The production support team receives an email when the deal goes live.  
Their process is to click on that link in order to open the engagement form directly from the email.  
Upon clicking the link they get "webpage cannot be found."
See email for further details.

**Comment by WorkMAE** [comment]
These should both be fixed now...it was missing SitePages in the link...

it was NACI/CI/Test2.aspx instead of NACI/CI/SitePages/Test2.aspx
