### ISSUE TITLE
User unable to submit form from draft

### ISSUE THREAD

**Issue by jacobdarling** [WorkMAE/CEM-Integration#24]
Another error happened for Richard today.  This time for Goodman International.  This time no error “number” when he tried to submit, only black screen and red box that error occurred.  He only entered one account number so should be unrelated to the other one..  See email for additional feedback

**Comment by WorkMAE** [comment]
This has now been corrected, the issue was occurring because it was looking for a number instead of a string value---drafts now save properly and then are deleted from the draft list once saved.
