### ISSUE TITLE
Parse Desktop / Completed / Purged panes

### ISSUE THREAD

**Issue by FourUnbelievableCoolKids** [WorkMAE/CEM-Integration#25]
As discussed, please create a separate frame at bottom of main page which will show only Completed and another for Purged PRJ records, leaving only Active, or "Desktop" deals in the original pane.  This will align with the future integration with the dashboard seamlessly as well as make deal management easier.

"Desktop" Pane:
- SIT
- UAT
- PVT
- Critical Care
- On Hold

"Completed" Pane:
- Live

"Purged" Pane
- Purged (need to add this)

**Comment by WorkMAE** [comment]
This will be be done in the test site as I have completely re-written how the grids get loaded and made them much easier to manage. I don't want to write code in the production site that will be a waste of time right now...

**Comment by WorkMAE** [comment]
This is now active in the test site and can be controlled via a button group that defaults to Active and includes Live and Purged buttons as well to toggle between them.

![image](https://user-images.githubusercontent.com/31932842/40561808-900651ec-602c-11e8-97fc-a34a7829593b.png)
