### ISSUE TITLE
Remove Filters on Landing Page

### ISSUE THREAD

**Issue by FourUnbelievableCoolKids** [WorkMAE/CEM-Integration#3]
Please remove the filters on the Landing Page on the Assigned Projects on all columns EXCEPT "Project Status".

Wish: Please add placeholder text "filter" to dropdown as default

**Comment by WorkMAE** [comment]
Will add in the default filter, will not remove other filters. Makes no sense to lessen functionality.  If someone wants to filter by something else or use multiple filters they can.  If they don't they can choose not to.
