### ISSUE TITLE
Deliver channel is not displaying when clicking on SWIFT Fin MT101 Message format

### ISSUE THREAD

**Issue by CIManager** [WorkMAE/CEM-Integration#30]
For Standard File Request Type: 

The only think that the user show see when clicking on SWIFT Fin MT101 Message is "Deliver Channel" with one option only (SWIFT Fin Concentrator).

**Comment by WorkMAE** [comment]
This should now be functioning properly:

When only SWIFT Fin Message is selected for Inbound File Format, there is no Outbound File Format or File Authorization panel, and only the Delivery Channel with SWIFT Fin Concentrator appears as an option.

![image](https://user-images.githubusercontent.com/31932842/41171288-0444e284-6b1e-11e8-86b6-af36e0f9ad96.png)
