### ISSUE TITLE
Standard Files issue - Delivery channel show disabear after unchecking all File Authorization options

### ISSUE THREAD

**Issue by CIManager** [WorkMAE/CEM-Integration#37]
Please make sure that the deliver channel disappears if non of the File Authorization options is selected.

**Comment by WorkMAE** [comment]
What happens in the case there is no file auth option, like with the SWIFT Fin 101 Message and it only has a delivery channel?

Or is this only the case where there are File Auth Options available, one must be selected before a delivery channel can be selected?

**Comment by WorkMAE** [comment]
This should be working as intended I believe...if SWIFT Fin 101 Message is selected only the Del Channel shows not the File auth panel.  In all other cases, the delivery channel only is shown after the File Authorization is selected.  

Please verify this is working properly now.

**Comment by FourUnbelievableCoolKids** [comment]
works
