### ISSUE TITLE
Unable to Edit Existing Item Passed Page 2

### ISSUE THREAD

**Issue by FourUnbelievableCoolKids** [WorkMAE/CEM-Integration#4]
For some reason, you cannot edit a deal and save/proceed at Page 2.

**Comment by FourUnbelievableCoolKids** [comment]
** this applies only to deals not created by user.  Perhaps "Edit" becomes disabled on deals if that's not desired, or check functionality for required fields disabling the button for Next Page

**Comment by WorkMAE** [comment]
No this shouldn't be the case.  What deal is it specifically so I can take a look, might be related to specific options selected.  Most likely is an issue with the hide/shows

**Comment by FourUnbelievableCoolKids** [comment]
I attempted to edit PRJ44564.  Upon review, it looks like this works as expected, presuming required format is met.  I didn't have enough characters in the ABC ID.  Closing now.
