### ISSUE TITLE
(ALL) HSBCConnect Form---ConGenRef Panel checkboxes are not unchecking when parent options are deselected

### ISSUE THREAD

**Issue by WorkMAE** [WorkMAE/CEM-Integration#46]
This should be resolved now, all checkboxes should uncheck when their parent object is unselected EXCEPT if there is a Non-US/CA Account selected since those have all options available.

**Comment by CIManager** [comment]
Still not working. For payable, the HSBC Connect Button is Hidden but the GenRef Panel checkboxes are still checked. Tested with Delivery channel options.

**Comment by FourUnbelievableCoolKids** [comment]
tested
