### ISSUE TITLE
Pause on Break ::: Transitions at Initial Load and Save/Submit

### ISSUE THREAD

**Issue by FourUnbelievableCoolKids** [WorkMAE/CEM-Integration#55]
jQuery.Deferred exception: Cannot read property 'getContext' of null TypeError: Cannot read property 'getContext' of null
    at HTMLDocument.<anonymous> (https://team.global.hsbc/sites/NACI/CI/SiteAssets/zDEV/scripts/landing.js:74:65)
    at l (https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:29375)
    at c (https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:29677) undefined
w.Deferred.exceptionHook @ jquery.min.js:2
c @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
u @ jquery.min.js:2
add @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
Deferred @ jquery.min.js:2
then @ jquery.min.js:2
w.fn.ready @ jquery.min.js:2
landParentCtrl @ landing.js:73
instantiate @ angular.js:4619
(anonymous) @ angular.js:9870
(anonymous) @ viewDirective.ts:413
ka @ angular.js:9492
u @ angular.js:8978
g @ angular.js:8226
(anonymous) @ angular.js:8106
(anonymous) @ angular.js:8447
updateView @ viewDirective.ts:332
configUpdatedCallback @ viewDirective.ts:263
configureUIView @ view.ts:261
ViewService.sync @ view.ts:271
activateViews @ views.ts:48
invokeCallback @ transitionHook.ts:147
TransitionHook.invokeHook @ transitionHook.ts:156
(anonymous) @ transitionHook.ts:118
TransitionHook.runAllHooks @ transitionHook.ts:118
transitionSuccess @ transition.ts:704
(anonymous) @ angular.js:15552
$eval @ angular.js:16820
$digest @ angular.js:16636
$apply @ angular.js:16928
g @ angular.js:11266
t @ angular.js:11464
u.onload @ angular.js:11405
load (async)
(anonymous) @ angular.js:11388
r @ angular.js:11235
g @ angular.js:10945
(anonymous) @ angular.js:15552
$eval @ angular.js:16820
$digest @ angular.js:16636
(anonymous) @ angular.js:16859
e @ angular.js:5804
(anonymous) @ angular.js:6081
setTimeout (async)
Zf.k.defer @ angular.js:6079
$evalAsync @ angular.js:16857
(anonymous) @ angular.js:15460
e @ angular.js:15568
$$resolve @ angular.js:15601
d @ angular.js:15611
l @ jquery.min.js:2
c @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
l @ jquery.min.js:2
c @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
l @ jquery.min.js:2
c @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
l @ jquery.min.js:2
c @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
l @ jquery.min.js:2
c @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
k @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
load (async)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
getUserData @ globalServices.js:201
(anonymous) @ router.js:287
l @ jquery.min.js:2
c @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
l @ jquery.min.js:2
c @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
k @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
load (async)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
getAllDeals @ globalServices.js:224
list @ router.js:279
invokeResolveFn @ resolvable.ts:121
(anonymous) @ angular.js:15552
$eval @ angular.js:16820
$digest @ angular.js:16636
(anonymous) @ angular.js:16859
e @ angular.js:5804
(anonymous) @ angular.js:6081
setTimeout (async)
Zf.k.defer @ angular.js:6079
$evalAsync @ angular.js:16857
(anonymous) @ angular.js:12033
setInterval (async)
f @ angular.js:12029
routerCtrl @ router.js:42
invoke @ angular.js:4604
T.instance @ angular.js:9855
u @ angular.js:8927
g @ angular.js:8226
(anonymous) @ angular.js:8106
(anonymous) @ angular.js:1696
$eval @ angular.js:16820
$apply @ angular.js:16920
(anonymous) @ angular.js:1694
invoke @ angular.js:4604
c @ angular.js:1692
Ac @ angular.js:1712
fe @ angular.js:1606
(anonymous) @ angular.js:30423
l @ jquery.min.js:2
c @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
_ @ jquery.min.js:2

jquery.min.js:2 Uncaught TypeError: Cannot read property 'getContext' of null
    at HTMLDocument.<anonymous> (landing.js:74)
    at l (jquery.min.js:2)
    at c (jquery.min.js:2)
(anonymous) @ landing.js:74
l @ jquery.min.js:2
c @ jquery.min.js:2
setTimeout (async)
w.readyException @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
l @ jquery.min.js:2
c @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
c @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
u @ jquery.min.js:2
add @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
Deferred @ jquery.min.js:2
then @ jquery.min.js:2
w.fn.ready @ jquery.min.js:2
landParentCtrl @ landing.js:73
instantiate @ angular.js:4619
(anonymous) @ angular.js:9870
(anonymous) @ viewDirective.ts:413
ka @ angular.js:9492
u @ angular.js:8978
g @ angular.js:8226
(anonymous) @ angular.js:8106
(anonymous) @ angular.js:8447
updateView @ viewDirective.ts:332
configUpdatedCallback @ viewDirective.ts:263
configureUIView @ view.ts:261
ViewService.sync @ view.ts:271
activateViews @ views.ts:48
invokeCallback @ transitionHook.ts:147
TransitionHook.invokeHook @ transitionHook.ts:156
(anonymous) @ transitionHook.ts:118
TransitionHook.runAllHooks @ transitionHook.ts:118
transitionSuccess @ transition.ts:704
(anonymous) @ angular.js:15552
$eval @ angular.js:16820
$digest @ angular.js:16636
$apply @ angular.js:16928
g @ angular.js:11266
t @ angular.js:11464
u.onload @ angular.js:11405
load (async)
(anonymous) @ angular.js:11388
r @ angular.js:11235
g @ angular.js:10945
(anonymous) @ angular.js:15552
$eval @ angular.js:16820
$digest @ angular.js:16636
(anonymous) @ angular.js:16859
e @ angular.js:5804
(anonymous) @ angular.js:6081
setTimeout (async)
Zf.k.defer @ angular.js:6079
$evalAsync @ angular.js:16857
(anonymous) @ angular.js:15460
e @ angular.js:15568
$$resolve @ angular.js:15601
d @ angular.js:15611
l @ jquery.min.js:2
c @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
l @ jquery.min.js:2
c @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
l @ jquery.min.js:2
c @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
l @ jquery.min.js:2
c @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
l @ jquery.min.js:2
c @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
k @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
load (async)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
getUserData @ globalServices.js:201
(anonymous) @ router.js:287
l @ jquery.min.js:2
c @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
l @ jquery.min.js:2
c @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
k @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
load (async)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
getAllDeals @ globalServices.js:224
list @ router.js:279
invokeResolveFn @ resolvable.ts:121
(anonymous) @ angular.js:15552
$eval @ angular.js:16820
$digest @ angular.js:16636
(anonymous) @ angular.js:16859
e @ angular.js:5804
(anonymous) @ angular.js:6081
setTimeout (async)
Zf.k.defer @ angular.js:6079
$evalAsync @ angular.js:16857
(anonymous) @ angular.js:12033
setInterval (async)
f @ angular.js:12029
routerCtrl @ router.js:42
invoke @ angular.js:4604
T.instance @ angular.js:9855
u @ angular.js:8927
g @ angular.js:8226
(anonymous) @ angular.js:8106
(anonymous) @ angular.js:1696
$eval @ angular.js:16820
$apply @ angular.js:16920
(anonymous) @ angular.js:1694
invoke @ angular.js:4604
c @ angular.js:1692
Ac @ angular.js:1712
fe @ angular.js:1606
(anonymous) @ angular.js:30423
l @ jquery.min.js:2
c @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
_ @ jquery.min.js:2

MainPage.js:895 undefined

MainPage.js:895 undefined

globalServices.js:296 {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
router.js:284 user: 20

**Comment by WorkMAE** [comment]
This is resolved, only loaded for Admin's and manager's where the charts are applicable for now
