### ISSUE TITLE
Deal Backup Access Not Functioning

### ISSUE THREAD

**Issue by FourUnbelievableCoolKids** [WorkMAE/CEM-Integration#57]
A test deal assigned from Foziah assigned to Chris does not show up for Chris.

**Comment by WorkMAE** [comment]
This is now functioning as intended.

**Comment by FourUnbelievableCoolKids** [comment]
Actually, now I can see the deal that was delegated to me (Hot Taco), but now the deals that were mine are gone.

**Comment by WorkMAE** [comment]
This should now be fixed 100%

**Comment by FourUnbelievableCoolKids** [comment]
test and works
