### ISSUE TITLE
Change Placeholder Text for PRJ

### ISSUE THREAD

**Issue by FourUnbelievableCoolKids** [WorkMAE/CEM-Integration#6]
Please adjust prepended PRJ_ with PRJ_0000 (all deals currently are prepended by 4 zeros, which will change to 3 in about 8 months.

**Comment by WorkMAE** [comment]
Will add this in and also validate that all deals must start with PRJ_0000 and not just PRJ_

**Comment by WorkMAE** [comment]
Completed
