### ISSUE TITLE
HSBC Contact data is not pulled from UserRoleList

### ISSUE THREAD

**Issue by CIManager** [WorkMAE/CEM-Integration#61]
The complete user contact info for the one who created the request and the one assigned is not showing automatically in the HSBC Contact List.

**Comment by WorkMAE** [comment]
All data should now be pulling, I just tested it.  The Position is populated but does not show for some reason unless it is double clicked on as if you are going to add something...unsure why that is, I will look for a fix for that.

**Comment by CIManager** [comment]
I confirm. All data is showing except the Position is not showing unless you double clicked it.
