### ISSUE TITLE
Bundle Code, Check Book Code(3 ch) and Check Book Code(5 ch) are not showing in the Payble view

### ISSUE THREAD

**Issue by CIManager** [WorkMAE/CEM-Integration#66]
Check Book Code(3 ch), Check Book Code(5 ch) and bundle code are not showing in the Payble view under US Accounts and Services

**Comment by WorkMAE** [comment]
This is now functioning

![image](https://user-images.githubusercontent.com/31932842/41425373-82bf7692-6fce-11e8-9b0c-125073864a12.png)
