### ISSUE TITLE
The entire H2H/FTP Connection is not showing in Payable view and....

### ISSUE THREAD

**Issue by CIManager** [WorkMAE/CEM-Integration#67]
The entire H2H/FTP Connection is not showing in Payable view and "<div class="ExternalClass61F5A53F955049A48FA16DAF2164F6A2">" needs to be hidden from Connection Comments. See "Urban Client" request.

**Comment by WorkMAE** [comment]
This should now be working and the H@H comments should now be showing without the HTML Markup included with it
