### ISSUE TITLE
Payable View - CNX 3rd Level Acknowledgement - 

### ISSUE THREAD

**Issue by CIManager** [WorkMAE/CEM-Integration#68]
Under:
Payable View
CNX3rd Level Acknowledgment 

Human Readable Report via HSBC Connect (H2H/FTP or SWIFTnet FileACT) is not showing

**Comment by WorkMAE** [comment]
These are all now showing properly

![image](https://user-images.githubusercontent.com/31932842/41426567-0181ecc8-6fd2-11e8-8fe6-0c4845de4ba3.png)

**Comment by FourUnbelievableCoolKids** [comment]
checked.
