### ISSUE TITLE
Background and Text Color in Input Fields

### ISSUE THREAD

**Issue by FourUnbelievableCoolKids** [WorkMAE/CEM-Integration#7]
Recommended to change in mainstyles.css ...

`input {
    background-color: rgba(215, 254, 254, 1) !important;
    color: #49484D !important;
}
`

**Comment by WorkMAE** [comment]
sent a pic of the requested changes and putting it up to a vote.  I have no dog in this fight, so whatever is decided I will make happen.

**Comment by WorkMAE** [comment]
This seems to not be an issue for anyone so I am closing.
