### ISSUE TITLE
Add Export as PDF Functionality

### ISSUE THREAD

**Issue by FourUnbelievableCoolKids** [WorkMAE/CEM-Integration#8]
These documents are ultimately used to produce a "handover document" to service, and are stored in the deal folder forever.  If this can be exported as a viewable PDF, that is ideal.

**Comment by WorkMAE** [comment]
You can currently do this by right clicking, choosing print and then choosing Nuance PDF as the printer.  Will clean up what it shows though as it is not as clean as it could be, has a bunch of extra stuff that prints with it.

**Comment by FourUnbelievableCoolKids** [comment]
I see what you mean.  Is it possible to add this as a standalone button from the Main Page (eg, Edit View Status Files PDF) where a super clean view appears and autoprompts the print options?

**Comment by WorkMAE** [comment]
Yep, I will set a print view that will only print what I have marked on that page which will just be the form itself. Should be able to do that relatively quickly..

**Comment by WorkMAE** [comment]
This is now fixed as good as I can make it for now.  I've added a Print View button at the top, if you click it, it pops up the print dialog, you can then save as a PDF and I managed to get rid of the blank page, so now it's just the form that prints out.

Once you click print, the window closes and you go back to the landing page.
