### ISSUE TITLE
Empty Table in Standard Form Connect Setup

### ISSUE THREAD

**Issue by FourUnbelievableCoolKids** [WorkMAE/CEM-Integration#82]
In the Standard File Connect for, a table populates with no options within it.  

![image](https://user-images.githubusercontent.com/33497892/42579789-0df41a78-84f7-11e8-9b5c-2d3c0c22bf09.png)

**Comment by WorkMAE** [comment]
Cannot reproduce issue...Standard File options load when proper pre requisites are checked
