### ISSUE TITLE
Dupe and Non-Assigned Deals in Dash After Subkit

### ISSUE THREAD

**Issue by FourUnbelievableCoolKids** [WorkMAE/CEM-Integration#86]
![image](https://user-images.githubusercontent.com/33497892/42586526-565b6708-8506-11e8-93c3-b4f8b56ecb81.png)

**Comment by WorkMAE** [comment]
https://github.com/WorkMAE/CEM-Integration/issues/77

**Comment by WorkMAE** [comment]
Believe this should now be resolved, it only adds project records to an empty list now so if it cycles through and there are already records added it skips them. Please test and verify.

**Comment by WorkMAE** [comment]
Still happening although much less frequently now, need to investigate further as to why this keeps happening.

**Comment by WorkMAE** [comment]
I believe this MAY be fixed now as it hasn't happened since I handled a previously unhandled transition error where it would try and transition back to the home page a second time when a transition was already happening.  Please let me know if you are still having issues with this.
