### ISSUE TITLE
date assigned issue

### ISSUE THREAD

**Issue by Mberrady** [WorkMAE/CEM-Integration#88]
Date assigned shows a previous date of when the dale was created
![image](https://user-images.githubusercontent.com/40861938/42901240-0f30b458-8a99-11e8-9b2b-22c00e713549.png)

**Comment by WorkMAE** [comment]
Mohmmed, I can't reproduce this issue...can you try and make this occur again?

**Comment by Mberrady** [comment]
It appears that it's working just fine
